language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V