version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon
      - PGDATA=/var/lib/postgresql/data
  # APP*****************************************
  amazon:
    image: amazon:latest
    network_mode: bridge
    container_name: amazon
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://postgres:5432/amazon
      - MYAPP_JDBC_USER=postgres
      - MYAPP_JDBC_PASS=postgres
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data: